######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

proc _main_ {} {
  cd "C:/Users/rchil/Desktop/Artemis/Software_desarrollado/Zynq/ADC_Read4/ADC_Read4.srcs/sources_1/edk/module_1"
  if { [ catch {xload xmp module_1.xmp} result ] } {
    exit 10
  }

  # Set host application type
  xset intstyle PA

  if { [catch {run clean} result] } {
    return -1
  }
  return $result
}

# Cleanup generated data
if { [catch {_main_} result] } {
  exit -1
}

# Check return status and exit
if { [string length $result] == 0 } {
  exit 0
} else {
  exit $result
}
