######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

cd "C:/Users/rchil/Desktop/Artemis/Software_desarrollado/Zynq/project_2/project_2.srcs/sources_1/edk/module_1"
if { [xload new module_1.xmp] != 0 } {
  exit -1
}
xset arch zynq
xset dev xc7z020
xset package clg484
xset speedgrade -1

xset binfo ZEDBOARD

if { [xset hier sub] != 0 } {
  exit -1
}
xset hdl vhdl
save proj
exit
